version: "3.8"
   
services:
  redis:
    image: redis
  
  database:
    image: postgres:9.6
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env/development/database
      - .env/development/web
    depends_on:
      - redis
      - database

volumes:
  db_data: