version: "3.8"
   
services:
  redis:
    image: redis
  
  database:
    image: postgres:9.6
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
  
  webpack:
    build: ./webpack
    command: ["npm", "start"]
    volumes:
      - ./webpack:/app
      - node-modules:/app/node_modules
      - webpack_build:/app/assets/bundles
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - webpack_build:/code/assets/bundles
    ports:
      - "8000:8000"
    env_file:
      - .env/development/database
      - .env/development/web
    depends_on:
      - redis
      - database

volumes:
  db_data:
  node-modules:
  webpack_build: