version: "3.8"
   
services:
  redis:
    image: redis
  
  database:
    image: postgres:9.6
    env_file:
      - env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
  
  webpack:
    build: ./webpack
    command: ["npm", "start"]
    volumes:
      - node-modules:/app/node_modules
      - ./${STATICFILES_DIRNAME}:/app/${STATICFILES_DIRNAME}/
  
  web:
    build: .
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
      - ./${STATICFILES_DIRNAME}:/code/${STATICFILES_DIRNAME}/
    ports:
      - "8000:8000"
    environment:
        - STATICFILES_DIRNAME=${STATICFILES_DIRNAME}
    env_file:
      - env/development/database
      - env/development/web

volumes:
  db_data:
  node-modules: